language: cpp
sudo: required
dist: trusty 
compiler: gcc

os:
  - linux

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  # Install oauth and libcurl library with headers
  - sudo apt-get install libcurl4-openssl-dev liboauth0 liboauth-dev

  # Install g++-6 
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  - ${CXX} --version


  # All dependcies are installed in ${TRAVIS_BUILD_DIR}/deps/
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
  
  # define boost version
  - BOOST_VERSION=1.63.0

  # Install Boost headers
  - |
    BOOST_DIR=${DEPS_DIR}/boost-${BOOST_VERSION}
    if [[ "${BOOST_VERSION}" == "trunk" ]]; then
      BOOST_URL="http://github.com/boostorg/boost.git"
      travis_retry git clone --depth 1 --recursive --quiet ${BOOST_URL} ${BOOST_DIR} || exit 1
      (cd ${BOOST_DIR} && ./bootstrap.sh && ./b2 headers)
    else
      BOOST_URL="http://sourceforge.net/projects/boost/files/boost/${BOOST_VERSION}/boost_${BOOST_VERSION//\./_}.tar.gz"
      mkdir -p ${BOOST_DIR}
      { travis_retry wget --quiet -O - ${BOOST_URL} | tar --strip-components=1 -xz -C ${BOOST_DIR}; } || exit 1
    fi                                                                            
  - CMAKE_OPTIONS+=" -DBOOST_ROOT=${BOOST_DIR}" 


  # Install a recent CMake
  - |
    CMAKE_URL="https://cmake.org/files/v3.7/cmake-3.7.2-Linux-x86_64.tar.gz"
    mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
    export PATH=${DEPS_DIR}/cmake/bin:${PATH}
  - cmake --version

  # Install Boost.Build
  - |
    (cd ${BOOST_DIR}/tools/build && ./bootstrap.sh && ./b2 install --prefix=${DEPS_DIR}/b2)
    export PATH=${DEPS_DIR}/b2/bin:${PATH}
    
env:
  - CONFIGURATION=Debug

before_script:
  # Go back to the root of the project and setup the build directory
  - cd ${TRAVIS_BUILD_DIR} 
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=$CONFIGURATION 
           ${CMAKE_OPTIONS}
          ..

script: make 

notifications:
  email:
    false

