language: cpp
sudo: required
dist: trusty 
compiler: gcc

os:
  - linux

env:
  global:
    - CONFIGURATION=Debug
    - CMAKE_OPTIONS=""

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  # Install oauth and libcurl library with headers
  - sudo apt-get install libcurl4-openssl-dev liboauth0 liboauth-dev

  # Install g++-6 
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  - ${CXX} --version


  # All dependcies are installed in ${TRAVIS_BUILD_DIR}/deps/
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
  
  # override boost version
  - BOOST_VERSION=1.64.0


# Download and install recent cmake
- |
  if [[ ${TRAVIS_OS_NAME} == "linux" ]]; then
    CMAKE_URL="https://cmake.org/files/v3.7/cmake-3.7.2-Linux-x86_64.tar.gz"
    mkdir -p ${DEPS_DIR}/cmake
    travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C ${DEPS_DIR}/cmake
    export PATH=${DEPS_DIR}/cmake/bin:${PATH}
  fi
- cmake --version


# Download and install Boost
- |
  if [[ ${TRAVIS_OS_NAME} == "linux" && ${BOOST_VERSION} != "default" ]]; then
    if [ ! -f "${DEPS_DIR}/boost/${BOOST_VERSION}_cached" ]; then
      # create dirs for source and install
      mkdir -p ${DEPS_DIR}/boost${BOOST_VERSION}
      mkdir -p ${DEPS_DIR}/boost
      rm -rf ${DEPS_DIR}/boost/*
      # download
      travis_retry wget --no-check-certificate --quiet -O - ${BOOST_URL} | tar --strip-components=1 -xz -C ${DEPS_DIR}/boost${BOOST_VERSION}
      pushd ${DEPS_DIR}/boost${BOOST_VERSION}
      # configure and install
      echo "using gcc : 4.8 : g++-4.8 ;" > $HOME/user-config.jam
      ./bootstrap.sh --prefix=${DEPS_DIR}/boost/ --with-libraries=program_options,filesystem,system,thread,test,timer,chrono
      ./b2 -d0 install
      popd
      touch ${DEPS_DIR}/boost/${BOOST_VERSION}_cached
    else
      echo 'Using cached Boost ${BOOST_VERSION} libraries.'
    fi
    export CMAKE_OPTIONS=${CMAKE_OPTIONS}" -DBOOST_ROOT=${DEPS_DIR}/boost"
  fi

script:
  # Go back to the root of the project and setup the build directory
  - cd ${TRAVIS_BUILD_DIR} 
  - mkdir build
  - cd build
  - echo ${CMAKE_OPTIONS}
  - cmake -DCMAKE_BUILD_TYPE=$CONFIGURATION 
          ${CMAKE_OPTIONS} 
          ..    
  - make


notifications:
  email:
    false

